### ISSUE TITLE
where is super_MLP.pkl

### ISSUE THREAD

**Issue by dudu070** [zhangxin1995/PTD#1]
{'method': 'local_CRF', 'dataset': {'path': './data/PTD/resnet50_visual_dataset.pkl'}, 'st_rerank': {'enable': False}, 'rerank': {'enable': False, 'k1': 1, 'k2': 2, 'lambda': 0.8}, 'adj2path': 'rnmf', 'dim': 2048, 'spatiotemporal': {'modelroot': './model/PTD/', 'locationroot': './data/PTD/location.json', 'name': 'super_MLP'}, 'cluster_threshold': 0.07, 'crf': {'alpha': 0.78, 'u': 0.1, 'T': 1, 'nc_threshold': 0, 'u1': 1.69, 'u2': 1.5, 'threshold': 0.9}}
Traceback (most recent call last):
  File "/home/duwenlong/person_reid_camera/PTD/code/main.py", line 25, in <module>
    main(config)
  File "/home/duwenlong/person_reid_camera/PTD/code/module/local_crf_main.py", line 489, in local_crf_main
    compare=generate_compare('UM',config['spatiotemporal']['name'],lm,name2idx,config['spatiotemporal']['modelroot'],convertname=True,thresh=th)
  File "/home/duwenlong/person_reid_camera/PTD/code/module/spatiotemporalmodel.py", line 139, in generate_compare
    compare=compare_factory[cn](locationmat[:,2],name2idx,locationmat[:,1],model=loadmodel(pathmodel_dir,'{}.pkl'.format(modelname)),convertname=convertname,**compare_parameters[cn])
  File "/home/duwenlong/person_reid_camera/PTD/code/module/spatiotemporalmodel.py", line 144, in loadmodel
    with open(p,'rb') as infile:
FileNotFoundError: [Errno 2] No such file or directory: './model/PTD/super_MLP.pkl'

**Comment by zhangxin1995** [comment]
You can use this link https://drive.google.com/file/d/1GPSSlPe6ZwFTNAzLOsOk1Li9DdYAvBkG/view?usp=sharing to download the corresponding model.

**Comment by dudu070** [comment]
This model looks problematic.

Traceback (most recent call last):
  File "/home/duwenlong/person_reid_camera/PTD/code/main.py", line 25, in <module>
    main(config)
  File "/home/duwenlong/person_reid_camera/PTD/code/module/local_crf_main.py", line 517, in local_crf_main
    score_gt,score_gt_length,score_cluster,score_cluster_length,args=LCTG.forward(threshold=config['cluster_threshold'],re_rank=config['rerank']['enable'],k1=config['rerank']['k1'],k2=config['rerank']['k2'],lambda_value=config['rerank']['lambda'])
  File "/home/duwenlong/person_reid_camera/PTD/code/module/local_crf_main.py", line 284, in forward
    after_info=self.generate_path(self.gts,self.gfs,self.tls,self.tcs,self.tidxs,inds,self.idx2pathidx,self.tpath2index,self.compare,self.dim,para)
  File "/home/duwenlong/person_reid_camera/PTD/code/module/local_crf_main.py", line 439, in generate_path
    fuzhu[i][j]=compare(sub_c[i],sub_t[i],sub_c[j],sub_t[j],prob=True)
  File "/home/duwenlong/person_reid_camera/PTD/code/module/spatiotemporalmodel.py", line 96, in __call__
    y_score=self.model.model.predict_proba(x)[:,1]
AttributeError: 'dict' object has no attribute 'model'

**Comment by zhangxin1995** [comment]
Sorry, I made a mistake with your question. Now that I have updated the repo, you can download the latest code through `git pull`, `super_ MLP.pkl` is now correctly located in the `code/model/PTD` directory.

**Comment by dudu070** [comment]
The version of scikit-learn in your project refers to the specific release or version of the library that you are using.

Warning: Cython evaluation is UNAVAILABLE
{'method': 'local_CRF', 'dataset': {'path': './data/PTD/resnet50_visual_dataset.pkl'}, 'st_rerank': {'enable': False}, 'rerank': {'enable': False, 'k1': 1, 'k2': 2, 'lambda': 0.8}, 'adj2path': 'rnmf', 'dim': 2048, 'spatiotemporal': {'modelroot': './model/PTD/', 'locationroot': './data/PTD/location.json', 'name': 'super_MLP'}, 'cluster_threshold': 0.07, 'crf': {'alpha': 0.78, 'u': 0.1, 'T': 1, 'nc_threshold': 0, 'u1': 1.69, 'u2': 1.5, 'threshold': 0.9}}
Traceback (most recent call last):
  File "/home/duwenlong/person_reid_camera/PTD/code/main.py", line 25, in <module>
    main(config)
  File "/home/duwenlong/person_reid_camera/PTD/code/module/local_crf_main.py", line 489, in local_crf_main
    compare=generate_compare('UM',config['spatiotemporal']['name'],lm,name2idx,config['spatiotemporal']['modelroot'],convertname=True,thresh=th)
  File "/home/duwenlong/person_reid_camera/PTD/code/module/spatiotemporalmodel.py", line 141, in generate_compare
    compare=compare_factory[cn](locationmat[:,2],name2idx,locationmat[:,1],model=loadmodel(pathmodel_dir,'{}.pkl'.format(modelname)),convertname=convertname,**compare_parameters[cn])
  File "/home/duwenlong/person_reid_camera/PTD/code/module/spatiotemporalmodel.py", line 150, in loadmodel
    res=pkl.load(infile,encoding='latin')
ModuleNotFoundError: No module named 'sklearn.neural_network.multilayer_perceptron'

**Comment by zhangxin1995** [comment]
This issue comes from an incompatible version of sklearn. You can install version 0.22.2. post1 of sklearn to see if it can be resolved.
